# Generated by Django 4.2 on 2024-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.CharField(choices=[('B', 'Balada'), ('S', 'Salsa'), ('R', 'Rock'), ('R', 'Reggaeton'), ('P', 'Pop'), ('V', 'Vallenato'), ('M', 'Merengue'), ('C', 'Clasico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
