# Generated by Django 4.2 on 2024-08-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_gender_alter_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.CharField(choices=[('P', 'Pop'), ('S', 'Salsa'), ('M', 'Merengue'), ('G', 'Reggaeton'), ('V', 'Vallenato'), ('R', 'Rock'), ('B', 'Balada'), ('C', 'Clasico')], max_length=30),
        ),
    ]
