# Generated by Django 4.2 on 2024-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_album_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.CharField(choices=[('M', 'Merengue'), ('B', 'Balada'), ('G', 'Reggaeton'), ('P', 'Pop'), ('S', 'Salsa'), ('C', 'Clasico'), ('V', 'Vallenato'), ('R', 'Rock')], max_length=30),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='album_images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(upload_to='artist_images/'),
        ),
    ]
