# Generated by Django 4.2 on 2024-08-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0004_alter_album_gender_alter_album_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_manager.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.CharField(choices=[('C', 'Clasico'), ('M', 'Merengue'), ('S', 'Salsa'), ('R', 'Rock'), ('G', 'Reggaeton'), ('V', 'Vallenato'), ('P', 'Pop'), ('B', 'Balada')], max_length=30),
        ),
    ]
