# Generated by Django 4.2 on 2024-08-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0005_alter_album_artist_alter_album_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.CharField(choices=[('P', 'Pop'), ('S', 'Salsa'), ('C', 'Clasico'), ('V', 'Vallenato'), ('B', 'Balada'), ('M', 'Merengue'), ('G', 'Reggaeton'), ('R', 'Rock')], max_length=30),
        ),
    ]
